### ISSUE TITLE
Put OM log files in its on folder

### ISSUE THREAD

**Issue by TAlonsoAmor** [SwissTPH/r-openMalariaUtilities#19]
Currently, all log/error files go to the log folder. OM produces lots of error/log files which makes it very difficult to find, for example, a log file related to the scenario creation or post-processing. 

Idea: Keep as it was done before, a separate folder for OM error/files and allow easy/fast access to error files for the scenario creation/ post-process and cleaning

**Comment by rogoersTPH** [comment]
Fixed in 700a65c
