### ISSUE TITLE
Add cluster dependencies

### ISSUE THREAD

**Issue by TAlonsoAmor** [SwissTPH/r-openMalariaUtilities#20]
Add dependencies to submit all 3,4 parts of the workflow to the cluster.

Description: When working at scicore or with multiples do_most files, not having dependencies allowing all jobs to be launched at the same time to the cluster, makes it easy for the user to make mistakes.

Example: 
* If my Rstudio session crushes, I need to 1. wait for it to be stable again to generate/launch next files, 2. load the experiment again to generate all the necessary paths. 
* If I'm working with 2 do_most at the same time, I need to be very careful to have the correct path names every time I'm launching a new job (otherwise I might be launching the same job twice and need to cancel and correct)

Ideas/References: Look at the run_script function from Munirflow

**Comment by rogoersTPH** [comment]
Fixed in 131b9e5
