### ISSUE TITLE
Remove SLURM interface?

### ISSUE THREAD

**Issue by rogoersTPH** [SwissTPH/r-openMalariaUtilities#21]
The interoperatibility with SLURM is done in a naive and opionated way. In fact, it is tailored for our group (Swiss TPH, AIM). 
However, this package is also intended for a general audience and they might (or probably) do not have access to a HPC running SLURM. Or their HPC is not using SLURM as a scheduler. 

In this light, it sounds reasonable to move this code into our internal repositories and make sure the functions for the scenario generation, simulation, etc. are designed in a way that they work nicely locally or in a HPC environment.

Related: #1

**Comment by ChristianSelinger** [comment]
I just wanted to report on odd behavior of slurm_simulation.sh, sometimes not all jobs are submitted, error message point towards lack of resources (i.e. executable) or impeded access to scenarios folder... one need to have some form of verbosity for the R slurm interface the let the user know about issues of job status etc.

**Comment by rogoersTPH** [comment]
Closed with [1c9d6e5](https://github.com/SwissTPH/r-openMalariaUtilities/commit/1c9d6e54c0e2c3810d3714e8329995b669e91387)
