### ISSUE TITLE
get_all_OMsimul looking for .Rdata files and not .RData

### ISSUE THREAD

**Issue by TAlonsoAmor** [SwissTPH/r-openMalariaUtilities#24]
I see get_all_OMsimul both on the munirflow and in openMalariaUtilities (if this does not belong here please let me know and I'll move it accordingly).
The function looks for .Rdata files but the new workflow produces .RData ones. 

From get_all_OMsimul

load(base::file.path(
      dir,
      base::paste0(
        "combined/", i,
        "_CombinedDat_Aggr.Rdata"
      )
    ))

**Comment by rogoersTPH** [comment]
This issue can only be solved in the internal package. I have created an issue there and will close this one.
