### ISSUE TITLE
Clarify path of experiment folder

### ISSUE THREAD

**Issue by JeanneLemant** [SwissTPH/r-openMalariaUtilities#27]
`createBaseXml(baseList, replace = TRUE)` creates an experiment folder in the current working directory, but it is not mentioned in the documentation of `createBaseXml`. It would be good to explicitly mention it as the munirflow was systematically creating experiment folders in "user/OpenMalaria/Experiments", which a naive user (i.e me) would expect.
I think the flexibility is good and should be kept, but just be explicit.

**Comment by rogoersTPH** [comment]
This should be done with [a6890ac](https://github.com/SwissTPH/r-openMalariaUtilities/commit/a6890ac46354e468ab73b77f30bed3c2b83a2fd5).
