### ISSUE TITLE
Function to erase errors and logs

### ISSUE THREAD

**Issue by JeanneLemant** [SwissTPH/r-openMalariaUtilities#28]
There was a `remove_errorfiles` function in the munirflow which was very practical when an experiment was rerun. Would it be possible to have an equivalent?

**Comment by rogoersTPH** [comment]
Should be fixed with [6b9baf5](https://github.com/SwissTPH/r-openMalariaUtilities/commit/6b9baf5c3cadb6bfe7daa7f70dd0a8e2bca33699).
