### ISSUE TITLE
Function to check if all placeholders of base XML are defined in scens

### ISSUE THREAD

**Issue by JeanneLemant** [SwissTPH/r-openMalariaUtilities#30]
The function `check_vars` in Munirflow was very practical to check if all the variables had been defined in `scens` before sending the jobs to the cluster. It is not optimal to have submit the job and then get the error that some variables are missing. Could this check be available before submission as well?

**Comment by JeanneLemant** [comment]
I am aware that the scenario generation does this, I just thought it was more practical when missing variables threw an error directly in the console before instead of after submitting to the cluster, when you have to open the right error log. To me that was in the spirit of "errors on the cluster are likely due to OpenMalaria or the workflow but not the user".

**Comment by rogoersTPH** [comment]
I see your point and I think this should be handled in a more involved way. What we need is the functionality to 

1. Validate your input. This includes the placeholders as well as the input list.
2. Print information about your experiment, e.g. which placeholders are used.

I would like to move this functionality into the next release as it likely requires more changes.

**Comment by rogoersTPH** [comment]
This should be done. The summary functionality is tracked in #55
